[build-system]
requires = ["setuptools>=64", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "metalfaiss"
version = "0.1.0"
description = "A pure Python port of FAISS using MLX and Metal JIT acceleration"